### ISSUE TITLE
Migrate this repository to openalea recipes

### ISSUE THREAD

**Issue by pradal** [VirtualPlants/tissuelab-conda-recipes#1]
The repository   [openalea-recipes](https://github.com/openalea/openalea-recipes) contains the full set of conda recipes for openalea.
I think that we can extend it with new packages either as a branch (tissuelab) or directly in the master using PR.
Users often use packages for OpenAlea with TissueLab. If they are not built together, this may create incompatbilities hard to solve.

**Comment by tkloczko** [comment]
Hi Christophe,

Actually, in order to provide a stable demo for the IPL, we need to hack some recipes from openalea so as to get packages built using develop versions of all the components that are required for tissuelab.

To avoid incompatibilities you mention, we created a dedicated channel on anaconda (tissuelab) that provides openalea packages built with the develop versions.

Of course, alternate ways to do it may be possible, at the moment it seems to be the simpliest way to do.

Cheers,

Thib

**Comment by pradal** [comment]
Hi Thibault,
I am currently working on a timagetk conda recipe.
While this solution works, we can also use (FYI) labels:
https://docs.continuum.io/anaconda-cloud/using#labels

Cheers
Christophe

**Comment by tkloczko** [comment]
Labels is great but it is not sufficient in the present case.

In fact, we would like to build a package from develop branch without breaking the current recipe. Ideally, it would be great if we could build a package from two different git branches using a single recipe. But clearly, it is not a feature of conda-build.

Of course, we can make a script hacking the meta.yaml file but is is quite ugly.

Considering that we need recipes for stable versions and nightly (or develop) versions, we can hav e two recipes for every package:
- one for stable version that is build from the master branch with the last tag as version number using Jinja
- one for the nightly version that is build from develop branch with dev string as version number

For instance, in the case of openalea.core recipe, we could have two folders, namely stable and nightly (or develop). Each folder would have its own meta.yaml file.

What do you think about that?

**Comment by tkloczko** [comment]
We just tried such an organization for package cellcomplex [here](https://github.com/VirtualPlants/tissuelab-conda-recipes/tree/master/cellcomplex).

It is not too complicated and it can be easily made automatic using continuous integration.

**Comment by pradal** [comment]
Excellent.
Or just using branches (branches solve everything....)

**Comment by tkloczko** [comment]
Thanks ;-) !

For the branches solution, I don't think it is a good idea. Given two branches, master and develop for the recipes, how to propagate a modification from one branch to another without breaking the fact that several parameters of the same recipe in the two branches are not the same. 

For instance, the git_tag parameter is different for master and develop, but if we want to change the about section which is the same, we have to perform the modification twice, once for each branch. This not the standard way to use branches :-) 

In the present case, we also need to do the modification twice but we clearly tell the developpers/users that it is two different parametrizations.
